spring:
  application:
    name: tech_app
  datasource:
    url: jdbc:mysql://localhost:3306/tech_app?useSSL=false
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: a123@!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false # ozun ucun arastirma et genis movzudu
    show-sql: true
    hibernate:
      ddl-auto: update